Fix compilation warning by removing unused variable [NFC]
clang complained with

../tools/clang/tools/extra/clangd/FS.cpp:19:12: error: unused variable 'Err' [-Werror,-Wunused-variable]
  if (auto Err = FS.makeAbsolute(PathStore))
           ^
1 error generated.

git-svn-id: https://llvm.org/svn/llvm-project/clang-tools-extra/trunk@343661 91177308-0d34-0410-b5e6-96231b3b80d8